import { Image5, Image6, Image7, Image1 } from "../../../../Assets/Images";

export default [
  {
    id: 1,
    Product: "Sport Gilet",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Green",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 25,
    Size: [24, 25, 26, 27, 28],
    color: "Green",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 2,
    Product: "Vibes Gilet",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 26,
    Size: [24, 25, 26, 27, 28],
    color: "Blue",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 3,
    Product: "Apex Jacket",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 27,
    Size: [24, 25, 26, 27, 28],
    color: "Yellow",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 4,
    Product: "Vibes Gilet",
    Manufacturer: "Manufacturer's name 4",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 28,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 5,
    Product: "Retake Jacket",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 24,
    Size: [24, 25, 26, 27, 28],
    color: "Black",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 6,
    Product: "Retake Jacket",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 25,
    Size: [24, 25, 26, 27, 28],
    color: "Black",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 7,
    Product: "Crest Padded Jacket",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 26,
    Size: [24, 25, 26, 27, 28],
    color: "Black",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 8,
    Product: "Crest Padded Vest",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 27,
    Size: [24, 25, 26, 27, 28],
    color: "Yellow",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 9,
    Product: "Speed Evolve Windbreaker",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 28,
    Size: [24, 25, 26, 27, 28],
    color: "Red",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 10,
    Product: "Retake Reversible Vest",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 28,
    Size: [24, 25, 26, 27, 28],
    color: "Blue",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 11,
    Product: "Retake Pullover Woven Jacket",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 24,
    Size: [24, 25, 26, 27, 28],
    color: "Yellow",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 12,
    Product: "Studio Jacket",
    Manufacturer: "Manufacturer's name 12",
    sales: 406.0,
    price: 316.0,
    Image1: Image1,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 25,
    Size: [24, 25, 26, 27, 28],
    color: "Green",
    createdAt: "2023-05-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 13,
    Product: "Sport Windbreaker",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 36.0,
    Image1: Image1,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 26,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-06-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 14,
    Product: "Sport Windbreaker",
    Manufacturer: "Manufacturer's name 14",
    sales: 406.0,
    price: 56.0,
    Image1: Image1,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 27,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 15,
    Product: "Vibes Fleece 1/4 Zip",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 28,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-12-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 16,
    Product: "Crest Padded Vest",
    Manufacturer: "Manufacturer's name",
    sales: 506.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 24,
    Size: [24, 25, 26, 27, 28],
    color: "Green",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 17,
    Product: "Retake Jacket",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 26,
    Size: [24, 25, 26, 27, 28],
    color: "Blue",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 18,
    Product: "Speed Evolve Windbreaker",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 27,
    Size: [24, 25, 26, 27, 28],
    color: "Blue",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 19,
    Product: "Vibes Gilet",
    Manufacturer: "Manufacturer's name",
    sales: 606.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 28,
    Size: [24, 25, 26, 27, 28],
    color: "Green",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
  {
    id: 20,
    Product: "Apex Jacket",
    Manufacturer: "Manufacturer's name",
    sales: 706.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Red",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 24,
    Size: [24, 25, 26, 27, 28],
    color: "Green",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "jackets",
  },
];
