import { Image5, Image6, Image7, Image1 } from "../../../../Assets/Images";

export default [
  {
    id: 41,
    Product: "Bold T-Shirt",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image7,
    Image2: Image6,
    Image3: Image5,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 25,
    Size: [24, 25, 26, 27, 28],
    color: "Blue",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 42,
    Product: "Bold Stringer",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 24,
    Size: [24, 25, 26, 27, 28],
    color: "Red",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 43,
    Product: "Power Washed T-Shirt",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 26,
    Size: [24, 25, 26, 27, 28],
    color: "Green",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 44,
    Product: "Power T-Shirt",
    Manufacturer: "Manufacturer's name 4",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 27,
    Size: [24, 25, 26, 27, 28],
    color: "Yellow",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 45,
    Product: "Legacy Stringer",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 28,
    Size: [24, 25, 26, 27, 28],
    color: "Blue",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 46,
    Product: "React T-Shirt",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 25,
    Size: [24, 25, 26, 27, 28],
    color: "Black",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 47,
    Product: "Legacy Stringer",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 24,
    Size: [24, 25, 26, 27, 28],
    color: "Red",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 48,
    Product: "Power T-Shirt",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 25,
    Size: [24, 25, 26, 27, 28],
    color: "Black",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 49,
    Product: "315 Woven Shorts",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 26,
    Size: [24, 25, 26, 27, 28],
    color: "Yellow",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 50,
    Product: "Power Washed 5 Shorts",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 27,
    Size: [24, 25, 26, 27, 28],
    color: "Yellow",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 51,
    Product: "Power Washed Short Sleeve Crew",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 28,
    Size: [24, 25, 26, 27, 28],
    color: "Yellow",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 52,
    Product: "Bold Drop Arm Tank",
    Manufacturer: "Manufacturer's name 12",
    sales: 406.0,
    price: 316.0,
    Image1: Image1,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 24,
    Size: [24, 25, 26, 27, 28],
    color: "Green",
    createdAt: "2023-05-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 53,
    Product: "Power T-Shirt",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 36.0,
    Image1: Image1,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 25,
    Size: [24, 25, 26, 27, 28],
    color: "Green",
    createdAt: "2023-06-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 54,
    Product: "React Drop Arm Tank",
    Manufacturer: "Manufacturer's name 14",
    sales: 406.0,
    price: 56.0,
    Image1: Image1,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 26,
    Size: [24, 25, 26, 27, 28],
    color: "Green",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 55,
    Product: "315 Seamless T-Shirt",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 27,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-12-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 56,
    Product: "315 Seamless Long Sleeve T-Shirt",
    Manufacturer: "Manufacturer's name",
    sales: 506.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 28,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 57,
    Product: "Essential Oversized Joggers",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 24,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 58,
    Product: "React 5 Shorts",
    Manufacturer: "Manufacturer's name",
    sales: 406.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 26,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 59,
    Product: "React Tank",
    Manufacturer: "Manufacturer's name",
    sales: 606.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 27,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
  {
    id: 60,
    Product: "Intergalactic Lifting Joggers",
    Manufacturer: "Manufacturer's name",
    sales: 706.0,
    price: 356.0,
    Image1: Image5,
    Image2: Image6,
    Image3: Image7,
    maincolor: "Blue",
    colors: "Red, Green, Yellow, Blue, Orange, Black",
    mainSize: 28,
    Size: [24, 25, 26, 27, 28],
    color: "Orange",
    createdAt: "2023-11-26",
    Features: "Hands-Free",
    Function: "Thrusting Rotation",
    Frequency: "10 Frequencies",
    Material: "TPE, ABS",
    Waterproof: "IPX5",
    ChargingTime: "210 mins",
    RunTime: "60 mins",
    InsertableLength: "4.33 in",
    Weight: "1.89 lbs",
    Description1:
      "165°adjustable rotating suction base aids you to enjoy various positions thrusting.",
    Description2:
      "Soft and raised texture inner sleeve assist you in enjoying 360°stimulation. 10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description3:
      "10 telescopic and rotating serve you enjoy the pleasure of oral sucking and vaginal friction.",
    Description4: "Detachable & Washable sleeve avoid hygienic Infection.",
    Description5:
      "Non-slip exterior help you hug her body tightly and won't slip off.",
    Description:
      "A hands-free automatic masturbator for those who are tired of jerking off with their hands and seek more accessories for solo play. When you open the masturbation cup, the automatic thrusting action and rich pellets lick your cock like crazy, stimulating every sensitive spot, and the gentle inner vaginal texture will make you feel like you're in a real pussy. The firm suction base allows you to place this penis massager on any smooth and hard surface, unlocking more locations like sticking this penis massager to a bedroom or bathroom wall. This is a realistic way to use penetrative sex. The hexagonal texture is non-slip and easy to grip to prevent falls.",
    Category: "lifting",
  },
];
